[book]
title = "企业架构设计方法与实践"
description = "关于如何进行企业架构设计的一些方法和实践"
authors = ["Tony Deng"]
language = "zh-CN"
multilingual = true
src = "."

[preprocessor.theme]
pagetoc = true
turn-off = true
root-font-size = "70%"
sidebar-width = "120px"
pagetoc-width = "15%"
content-max-width = "80%"


[output.html]
additional-css = ["theme/simple-lightbox.css", "theme/theme.css", "theme/pagetoc.css"]
additional-js = ["theme/simple-lightbox.min.js","theme/theme.js", "theme/pagetoc.js"]
git-repository-url = "https://github.com/tonydeng/EA-practices"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[output.html.print]
enable = false

[build]
build-dir = "_book"